name: Sync GH Pages
on:
  push:
    branches:
      - main
    paths:
      - library/**

permissions: read-all

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: "gh-pages"
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
